package org.manuel.mysportfolio.model.entities.player;

// https://en.wikipedia.org/wiki/Association_football_positions
public enum FootballPosition {

  KEEPER, LEFT_BACK, RIGHT_BACK, LEFT_CENTER_BACK, RIGHT_CENTER_BACK, SWEEPER,
  DEFENSIVE_MIDFIELDER, OFFENSIVE_MIDFIELDER, LEFT_CENTER_MIDFIELDER, RIGHT_CENTER_MIDFIELDER,
  LEFT_MIDFIELDER, RIGHT_MIDFIELDER,
  LEFT_WINGER, RIGHT_WINGER, CENTRE_FORWARD, SECOND_STRIKER

}
