info.app.name: mysportfolio
info.app.description: Sportfolio backend app
info.app.version: ${VERSION:unknown}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/mysportfolio}