info.app:
  name: mysportfolio
  description: MySportfolio backend

server:
  port: 8090

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/mysportfolio}
      auto-index-creation: true